[package]
name = "picostream"
version = "0.1.0"
edition = "2021"

[dependencies]
picostream-shared = { path = "../shared" }

nusb = "0.2"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
libc = "0.2"
