# Default target is RP2040. For RP235x, use:
#   cargo run --release --target thumbv8m.main-none-eabihf --no-default-features --features rp235x

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP235x"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
